### ISSUE TITLE
ValueError: Error when checking : expected reshape_1_input to have shape (None, 16, 8) but got array with shape (1, 16, 16)

### ISSUE THREAD

**Issue by vvvhung** [li-s/Handwriting-recognition#9]
I run
`python3 predict.py [image_path]`

with image 
https://raw.githubusercontent.com/li-s/Handwriting-recognition/master/data/show_image0.jpg

`Traceback (most recent call last):
  File "predict.py", line 38, in <module>
    result_alphabet, confidence = predict(model_config, file_location)
  File "predict.py", line 23, in predict
    prediction = model.predict(x_test, batch_size=32, verbose=0)
  File "/Users/louis/Documents/PYTHON3.6/OCR_VENV/lib/python3.6/site-packages/keras/models.py", line 1025, in predict
    steps=steps)
  File "/Users/louis/Documents/PYTHON3.6/OCR_VENV/lib/python3.6/site-packages/keras/engine/training.py", line 1817, in predict
    check_batch_axis=False)
  File "/Users/louis/Documents/PYTHON3.6/OCR_VENV/lib/python3.6/site-packages/keras/engine/training.py", line 123, in _standardize_input_data
    str(data_shape))
ValueError: Error when checking : expected reshape_1_input to have shape (16, 8) but got array with shape (16, 16)
`

**Comment by vvvhung** [comment]
I change resize to (16, 8) and it works.
